### ISSUE TITLE
编译环境相关参数

### ISSUE THREAD

**Issue by doubledeft** [stark81/VutronMusic#31]
**Describe the bug**
m1 mac 使用 node js v20.13.1或 yarn 1.22.22无法编译，需要提供编译相关环境参数
**To Reproduce**

**Expected behavior**

**Device information (please complete the following information):**
 - OS Name: [e.g. Windows, macOS, Linux...]
 - OS Version: [e.g. 11, 10.14...]

**Screenshots & Attachments**

**Additional context**

**Comment by doubledeft** [comment]
修改后yarn install 报错。报错内容如下：
yarn install 
yarn install v1.22.22
warning ../../../../package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > vue-draggable-plus@0.5.4" has unmet peer dependency "@types/sortablejs@^1.15.0".
warning "electron-builder > app-builder-lib@24.13.3" has unmet peer dependency "electron-builder-squirrel-windows@24.13.3".
[5/5] 🔨  Building fresh packages...
[1/5] ⢀ better-sqlite3
[-/5] ⢀ waiting...
[3/5] ⢀ esbuild
[-/5] ⢀ waiting...
error VutronMusic/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: VutronMusic/node_modules/electron
Output:
RequestError
    at ClientRequest.<anonymous> (/VutronMusic/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:531:35)
    at origin.emit (VutronMusic/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)AggregateError [ETIMEDOUT]:

**Comment by stark81** [comment]
error VutronMusic/node_modules/electron: Command failed.：这表明在安装 Electron 时发生了错误。
RequestError 和 AggregateError [ETIMEDOUT]：这个错误通常表示网络请求超时，可能是由于网络连接不稳定或无法访问某个依赖项的服务器。

你看看是不是自己没有设置electron源

**Comment by doubledeft** [comment]
设置后就好了，这是我build出来的arm64的包，fork了一份放在release里了https://github.com/doubledeft/VutronMusic/releases

**Comment by stark81** [comment]
最后提一下，之前版本里的store/player.ts里还有听歌记录的功能，这个功能会导致封号的风险，现在最新版本暂时把这个功能屏蔽了，建议看看你打包的那个版本里有没有屏蔽哦。。

**Comment by doubledeft** [comment]
更新了，更新后的打包传上去了
<img width="1243" alt="image" src="https://github.com/user-attachments/assets/e5d394ed-7dfc-4a0c-a0df-1ee3b4f78023">
